name: Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3 # Check for linting issues
        with:
          version: latest
      - uses: astral-sh/ruff-action@v3 # Check for formatting issues
        with:
          version: latest
          args: "format --check"
